language: python
sudo: required

matrix:
  include:

    - os: osx
      osx_image: xcode10.2
      language: generic
      env: PYTHON=3.6.0

    - os: osx
      osx_image: xcode11.3
      language: generic
      env: CONDA=3.6

    - os: linux
      dist: xenial
      python: 3.6
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - 'libopenmpi-dev'
            - 'openmpi-bin'

    # Modern toolsets
    - os: linux
      dist: xenial
      python: 3.7
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - 'libmpich-dev'
            - 'mpich'

    - os: linux
      dist: xenial
      python: 3.8
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - 'libopenmpi-dev'
            - 'openmpi-bin'

before_install:
  - |
     if [ -n "$CONDA" ]; then
       if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
       wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
       bash miniconda.sh -b -p $HOME/miniconda
       export PATH="$HOME/miniconda/bin:$PATH"
       conda config --set always_yes yes --set changeps1 no
       conda update -q conda
       conda install -q conda-build
       conda env create --file environment.yml
       source activate netket_env
     # When Travis starts supporting `addons: brew: packages: [...]` correctly,
     # this can be move this into the build matrix.
     elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update
       brew ls --versions openmpi && brew upgrade openmpi || brew install openmpi
       brew ls --versions pyenv && brew upgrade pyenv || brew install pyenv

       # Force OS X to use the correct python version. This is only because
       # Travis' support for `language: python` on OS X is too buggy.

       PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install $PYTHON
       # This part is (apparently) quite important! As per the docs it makes
       # pyenv aware that some executables have been installed/removed. Without it
       # `pyenv global` won't be able to find the version of Python we're asking for.
       pyenv rehash
       # Printing the info about pyenv's python version before and after the change.
       # We should see something like `system` before and `3.6.0` after.
       pyenv global
       pyenv global $PYTHON
       pyenv global
       # Manually update the PATH as advised in the pyenv docs.
       PATH="$(pyenv root)/shims:$PATH"
       # OS X build have `language: generic` so `TRAVIS_PYTHON_VERSION` is undefined
       # at first.
       TRAVIS_PYTHON_VERSION=$PYTHON
     fi
  - |
     if ! which pip; then
       python -m easy_install pip
     fi

install:
  - python --version
  - python -m pip install -U pip
  - python -m pip --version
  - python -m pip install networkx 'pytest==5.3' python-igraph jax jaxlib black
  - |
    if [ -n "$CONDA" || $TRAVIS_OS_NAME != "osx" ]; then
      python -m pip install torch
    fi
  - |
    if [ -z "$CONDA" ]; then
      python -m pip install mpi4jax
    fi
  - python -m pip install pytest-xdist
  - python -m pytest --version
  - python -m pip install -v .
  - mkdir workdir && cd workdir

script:
  - python -c 'import netket'
  - python -m pytest --durations=0 -n 2 --verbose ../Test/
  - mpirun -np 2 python -m pytest --durations=0 --verbose ../Test_MPI
  # - python -m pytest --durations=0 --verbose --doctest-glob='*.md' ../Docs/
