name: "Website"

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # Determine the branch name
    - uses: mdecoleman/pr-branch-name@1.0.0
      id: determine-branch
      if: ${{ github.event_name == 'pull_request'Â }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Pip install python dependencies
      run: |
        pip install -e ".[dev]"

    - name: Install docs dependencies and Pandoc
      run: |
        sudo apt-get -y install pandoc
        pip install -r docs/requirements.txt

    - name: Make docs
      run: |
        cd docs 
        make html

    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      if: github.event.pull_request.head.repo.full_name != 'netket/netket'
      with:
        name: DocumentationHTML
        path: docs/_build/html/

    # Publish built docs to gh-pages branch.
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy Website and Docs
      if: success() && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        cname: www.netket.org

    - name: Deploy Website and Docs Preview
      if: (success() && github.ref != 'refs/heads/master' && github.event.pull_request.head.repo.full_name == 'netket/netket' ) && !contains(github.event.pull_request.labels.*.name, 'dependencies')
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        destination_dir: preview/${{ steps.determine-branch.outputs.branch }}

    - name: Comment on PR 
      if: success() && github.ref != 'refs/heads/master' && github.event.pull_request.head.repo.full_name == 'netket/netket' 
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        message: |
          Hello and thanks for your Contribution!
          I will be building previews of the updated documentation at the following link:
          https://netket.github.io/netket/preview/${{ steps.determine-branch.outputs.branch }}

          Once the PR is closed or merged, the preview will be automatically deleted.
