name: Check Formatting & Flakes

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    name: Check Formatting

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Pip install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -v black==22.3.0

      - name: Black Code Formatter
        run: black --check --diff --color .

  flakes:
    name: Check Flake8

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Pip install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -v flake8==5.0.4

      - name: Black Code Formatter
        run: flake8 --exclude=Examples/Legacy Examples netket
